import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/styles/globals.scss'
import LeafBgLayout from '@/components/layout/LeafBgLayout'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'KJW Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <LeafBgLayout>{children}</LeafBgLayout>
      </body>
    </html>
  )
}
